### ISSUE TITLE
On startup tmpsong info is wrong

### ISSUE THREAD

**Issue by noiz** [alaingilbert/ttapi#11]
I am looking at trying to check the endsong event and I noticed that on startup the first endsong event we get has different data than after we have already been running.  I narrowed the issue down to this line: https://github.com/alaingilbert/ttapi/blob/master/ttapi.go#L286  In my initial testing I changed that line to be `b.setTmpSong(roomInfoHash["room"].(map[string]interface{}))` to match what is sent for normal song changes here: https://github.com/alaingilbert/ttapi/blob/master/ttapi.go#L219  With that hacky fix I can always get the same json map that I can parse the same way both time.  I know there should be some error checking in the fix and not sure how you want to handle that, but if we could get the startup info to match the song change info that would fix the issue I am having parsing the endsong event correctly every time.

**Comment by alaingilbert** [comment]
You're totally right, I pushed a fix here -> https://github.com/alaingilbert/ttapi/commit/1b5cfd0f8166fa55bc7688691442a0ebecee86c5

**Comment by noiz** [comment]
Cool, fix is working, thanks!
