### ISSUE TITLE
Bot goes offline and online constantly when you try and PM it

### ISSUE THREAD

**Issue by noiz** [alaingilbert/ttapi#3]
Hey, think I debugged this issue down to the root cause.  Right now it looks like ttapi is only sending a presence update when it receives a heartbeat message from the server or when there is no session.  From inspecting the web traffic in Chrome we should actually be sending the presence update every 10 seconds (or whatever interval the server is returning).  I see right now by inspecting the websocket from Chrome that I am normally sending a presence update every 10 seconds as seen below:

![image](https://user-images.githubusercontent.com/500879/122297459-6476b800-ceb0-11eb-8b84-f10c6704df69.png)

I see in the logrus output when I turn on debug logs that every time ttapi sends out a presence update that a message is returned with an interval that ttapi is then not using:

```
DEBU[0135] < {"api":"presence.update","client":"web","clientid":"dunno_if_this_is_secret","msgid":20,"status":"available","userauth":"edited_this_out","userid":"edited_this_out_too"} 
DEBU[0135] > ~m~72~m~{"msgid": 20, "now": 1623878255.079107, "success": true, "interval": 10} 
```
Can we update ttapi to send the presence update at the correct interval?  I believe that should fix the issue.  For now I just started a goroutine that is sending a presence update manually every 10 seconds and that fixed the issue but I feel like ttapi should properly fix this as well for anyone else that wants to use this library.

**Comment by alaingilbert** [comment]
I pushed a fix, I didn't try it but I think it should work
https://github.com/alaingilbert/ttapi/commit/247990d5f4564b27c63f70c799b8ea4cbd70869f

**Comment by noiz** [comment]
Yup, looks like that did the trick, no longer seeing the issue.  Thanks for the quick turnaround on this!
